<template>
  <div class="flex justify-evenly text-xs my-1">
    <div class="flex flex-col items-center text-belstarRed justify-center">
      <h3>帳單消費分期</h3>
      <img
        src="https://www.cognex.com/api/Sitecore/Barcode/Get?data=This%20is%20a%20QR%20Code%20by%20Cognex&code=Z_QR_CODE&width=100&imageType=JPG&foreColor=%23000000&backColor=%23FFFFFF&rotation=RotateNoneFlipNone"
        alt="Barcode generated by Cognex Corporation"
        width="55"
      />
    </div>
    <div class="flex flex-col items-center text-belstarRed justify-center">
      <h3>網路/ATM預借現金</h3>
      <img
        src="https://www.cognex.com/api/Sitecore/Barcode/Get?data=This%20is%20a%20QR%20Code%20by%20Cognex&code=Z_QR_CODE&width=100&imageType=JPG&foreColor=%23000000&backColor=%23FFFFFF&rotation=RotateNoneFlipNone"
        alt="Barcode generated by Cognex Corporation"
        width="55"
      />
    </div>
  </div>
</template>
